Repository micronaut-projects/micronaut-guides, pull requests merged in 2023-10, with the labels that each got.

#1354 improve detection whether is Java GraalVM
  buildSrc/src/main/groovy/io/micronaut/guides/GuidesPlugin.groovy
Labels: relates-to: graal

#1355 link to Oracle GraalVM license and GraalVM CE
  src/docs/common/snippets/common-install-graalvm-sdkman.adoc
Labels: relates-to: graal

#1363 Fix the exit code check in native test scripts
  buildSrc/src/main/groovy/io/micronaut/guides/TestScriptGenerator.groovy
Labels: bug

#1364 AWS Lambda Java 17 runtime
  guides/micronaut-aws-lambda-eventbridge-event/micronaut-aws-lambda-eventbridge-event.adoc
  guides/micronaut-aws-lambda-s3-event/micronaut-aws-lambda-s3-event.adoc
  guides/micronaut-aws-secretsmanager-rotation/micronaut-aws-secretsmanager-rotation.adoc
  guides/mn-application-aws-lambda-java-runtime/metadata.json
  guides/mn-application-aws-lambda-java-runtime/mn-application-aws-lambda-java-runtime.adoc
  guides/mn-serverless-function-aws-lambda/metadata.json
  guides/mn-serverless-function-aws-lambda/mn-serverless-function-aws-lambda.adoc
Labels: type: docs
